# Workflow name
name: QA EDW
on:
  workflow_dispatch:
  push:
    paths:
      - edw/ddl_scripts/qa/**
      - edw/bigquery_table_security_qa.json
    branches-ignore: [$default-branch]
env:
  ####### CONSTANT VALUES #######
  VAULT_URL: https://vault.genmills.com:8200
  ####### VALUES CHANGE PER ENVIRONMENT #######
  PROJECT_ID: edw-qa-c89f9d
  ROLESET_PATH: gcp-edw-qa/key/build-edw-qa-<your project>
  TABLE_LEVEL_SECURITY_FILE_PATH: ./edw/bigquery_table_security_qa.json
  JWT_ROLE_QA: gmi-common-<your project>-dlf-gcp-build-qa
permissions:
  id-token: write
  contents: read
jobs:
  deploy-edw-qa:
    runs-on: gcp
    environment: qa
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Fetch Vault Token
      uses: hashicorp/vault-action@v2
      with:
        url: ${{ env.VAULT_URL }}
        caCertificate: ${{ secrets.VAULT_CERT }}
        method: jwt
        path: oidc-github
        role: ${{ env.JWT_ROLE_QA }}
        jwtGithubAudience: https://github.com/gmi-common
        exportToken: true
        secrets: |
          secret/data/cloverleaf/github/prod/github-database-portal-client-id value | DATABASE_PORTAL_CLIENT_ID;
          secret/data/cloverleaf/github/prod/github-database-portal-client-secret value | DATABASE_PORTAL_CLIENT_SECRET;
    - name: Deploy edw qa
      uses: gmi-actions/bigquery-ddl-deploy-action@v1
      with:
        google_project_id: ${{ env.PROJECT_ID }}
        ddl_folder_path: |
          ./edw/ddl_scripts/qa
        bigdata_mongo_user: ${{ secrets.DATADEPLOY_MONGO_USER }}
        bigdata_mongo_password: ${{ secrets.DATADEPLOY_MONGO_PASSWORD }}
        vault_token: ${{ env.VAULT_TOKEN }}
        roleset_path: ${{ env.ROLESET_PATH }}
        debug: True
    - name: EDW table security
      uses: gmi-actions/gcp-bq-table-security-action@v2
      with:
        table_security_file: ${{ env.TABLE_LEVEL_SECURITY_FILE_PATH}}
        azure_client_id: ${{ env.DATABASE_PORTAL_CLIENT_ID }}
        azure_client_secret: ${{ env.DATABASE_PORTAL_CLIENT_SECRET }}
        azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
